"""Claims ledger: every number the README states is checked against the results files.

The ledger format and checker come from Morpheus (kai9987kai/morpheus, MIT), which took them
from Ghost in the Machine. ``claims/claims.json`` lists each claim, its status and the numbers
it quotes; each number names a results file, a JSON pointer into it, the value as stated and its
rounding. ``check`` resolves every pointer, verifies the rounding, and verifies that the README
table is exactly what the ledger renders. Failed and unsupported claims stay in the ledger.

    prometheus claims check
    prometheus claims render
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
LEDGER = ROOT / "claims" / "claims.json"
README = ROOT / "README.md"
START = "<!-- claims:start (generated by `prometheus claims render`; edit claims/claims.json) -->"
END = "<!-- claims:end -->"


def resolve(doc, pointer: str):
    cur = doc
    for raw in pointer.lstrip("/").split("/"):
        key = raw.replace("~1", "/").replace("~0", "~")
        cur = cur[int(key)] if isinstance(cur, list) else cur[key]
    return cur


def fmt(v, decimals):
    if isinstance(v, (bool, str)) or decimals is None:
        return str(v)
    if decimals == "int":
        return str(int(round(v)))
    if decimals == "sci":
        return f"{v:.1e}"
    return f"{v:.{decimals}f}"


def load(path=LEDGER):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def check_numbers(ledger) -> list[str]:
    errors, cache = [], {}
    for c in ledger["claims"]:
        for name, ev in c.get("evidence", {}).items():
            try:
                doc = cache.setdefault(ev["file"], json.loads((ROOT / ev["file"]).read_text(encoding="utf-8")))
                actual = resolve(doc, ev["pointer"])
            except (OSError, KeyError, IndexError, ValueError, TypeError) as e:
                errors.append(f"{c['id']}.{name}: cannot resolve {ev['file']}#{ev['pointer']} ({e!r})")
                continue
            d = ev.get("decimals", 2)
            if fmt(actual, d) != fmt(ev["value"], d):
                errors.append(f"{c['id']}.{name}: stated {fmt(ev['value'], d)} but {ev['file']}#{ev['pointer']} "
                              f"is {actual!r} (renders {fmt(actual, d)})")
    return errors


def evidence_text(c) -> str:
    vals = {k: fmt(ev["value"], ev.get("decimals", 2)) for k, ev in c.get("evidence", {}).items()}
    return c["evidence_text"].format(**vals)


def rendered_rows(ledger=None):
    ledger = ledger or load()
    return [{"id": c["id"], "status": c["status"], "claim": c["claim"], "evidence": evidence_text(c),
             "headline": c.get("headline", False)} for c in ledger["claims"]]


def table(ledger) -> str:
    lines = ["| claim | status | evidence |", "|---|---|---|"]
    for r in rendered_rows(ledger):
        claim = f"**{r['claim']}**" if r["headline"] else r["claim"]
        lines.append(f"| {claim} | **{r['status']}** | {r['evidence']} |")
    return "\n".join(lines)


def _block(ledger) -> str:
    return f"{START}\n\n{table(ledger)}\n\n{END}"


def main(action: str) -> int:
    ledger = load()
    text = README.read_text(encoding="utf-8")
    if START not in text or END not in text:
        print("README has no claims markers")
        return 1
    i, j = text.index(START), text.index(END) + len(END)
    if action == "render":
        README.write_text(text[:i] + _block(ledger) + text[j:], encoding="utf-8")
        print("rendered README claims table")
        return 0
    errors = check_numbers(ledger)
    if text[i:j] != _block(ledger):
        errors.append("README claims table differs from the ledger; run `prometheus claims render`")
    for e in errors:
        print("FAIL", e)
    if not errors:
        n = sum(len(c.get("evidence", {})) for c in ledger["claims"])
        print(f"ok: {len(ledger['claims'])} claims, {n} numbers verified against results")
    return 1 if errors else 0
